FROM node:latest

ENV PROTO_HOME="/.proto"
ENV PATH="$PROTO_HOME/shims:$PROTO_HOME/bin:$PATH"
ENV SHELL=/bin/bash
ENV NODE_ENV=production
ENV QUART_ENV=production
ENV NODE_OPTIONS=--max-old-space-size=8192

RUN mkdir -p /app
ADD . /app
ADD .prototools .
ADD .moon .moon
WORKDIR /app

RUN npm install -g @moonrepo/cli
RUN curl -fsSL https://moonrepo.dev/install/proto.sh | bash
RUN proto use

RUN bash -c 'yes | moon :build'

ENTRYPOINT [ "/app/entrypoint.sh" ]