packages:
  - packages/*
  - apps/*
  - "!**/test/**"
onlyBuiltDependencies:
  - "@nestjs/core"
  - "@swc/core"
  - argon2
  - canvas
  - core-js
  - esbuild
catalog:
  "@eslint/eslintrc": ^3.3.1
  "@eslint/js": ^9.18.0
  "@faker-js/faker": ^9.9.0
  "@headlessui/react": ^2.2.7
  "@heroicons/react": ^2.2.0
  "@hookform/resolvers": ^5.2.1
  "@nestjs/cli": ^11.0.0
  "@nestjs/common": ^11.0.1
  "@nestjs/config": ^4.0.2
  "@nestjs/core": ^11.0.1
  "@nestjs/jwt": ^11.0.0
  "@nestjs/platform-express": ^11.0.1
  "@nestjs/schematics": ^11.0.0
  "@nestjs/swagger": ^11.2.0
  "@nestjs/testing": ^11.0.1
  "@nestjs/typeorm": ^11.0.0
  "@swc/cli": ^0.6.0
  "@swc/core": ^1.10.7
  "@tailwindcss/postcss": ^4
  "@types/express": ^5.0.0
  "@types/factory-girl": ^5.0.12
  "@types/jest": ^29.5.14
  "@types/lodash": ^4.17.20
  "@types/node": ^24
  "@types/react": ^19
  "@types/react-dom": ^19
  "@types/supertest": ^6.0.2
  argon2: ^0.43.1
  class-transformer: ^0.5.1
  class-validator: ^0.14.2
  clsx: ^2.1.1
  dotenv: ^17.2.1
  eslint: ^9
  eslint-config-next: 15.4.5
  eslint-config-prettier: ^10.0.1
  eslint-plugin-prettier: ^5.2.2
  factory-girl: ^5.0.4
  globals: ^16.0.0
  jest: ^29.7.0
  lodash: ^4.17.21
  next: 15.4.5
  pg: ^8.16.3
  prettier: ^3.4.2
  prettier-plugin-tailwindcss: ^0.6.14
  react: 19.1.0
  react-dom: 19.1.0
  react-hook-form: ^7.62.0
  react-hot-toast: ^2.5.2
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.1
  source-map-support: ^0.5.21
  supertest: ^7.0.0
  tailwindcss: ^4
  ts-jest: ^29.2.5
  ts-loader: ^9.5.2
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  typeorm: ^0.3.25
  typescript: ^5.8
  typescript-eslint: ^8.20.0
  vitest: ^3.2.4
  zod: ^4.0.14
