name: "ci"

on:
  - pull_request
permissions: write-all

jobs:
  moon_ci:
    environment: action-testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'setup'
        run: 'proto use'
      - name: moon-ci
        run: 'moon ci --color'
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
      - uses: appthrust/moon-ci-retrospect@v1
        if: success() || failure()
      - uses: 'moonrepo/run-report-action@v1'
        if: success() || failure()
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}